#!/bin/bash
which go || echo "Please install go"  exit 1
go build -o fchroot src/mainmain.go
sudo cp fchroot /usr/sbin/

echo "Заменить artix-chroot на fast-chroot"
read -p "[Y/n]>>>:  "  -n 1 -r
if [[ $REPLY =~ ^[Yy]$ ]] || [[ -z $REPLY ]]; then
    echo "Используем fchroot"
    sudo ln -sf /usr/sbin/fchroot /usr/sbin/artix-chroot
else
    echo "Оставляем artix-chroot"
fi
